# Server Config
server.port=8080
server.servlet.context-path=

# DataSource Config
spring.datasource.url=jdbc:h2:mem:security_sociale;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# JPA/Hibernate Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:schema-data.sql

# JWT Config
# 256-bit Hex Key for Token Generation
app.jwtSecret=5367566B58703273357638792F423F4528482B4D6251655468576D5A71347437
# Expiration: 7 Days (604800000 ms)
app.jwtExpirationInMs=604800000

# OpenAPI/Swagger Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
